site_name: Developer Documentation
site_description: Translation and documentation of programming tools
site_url: https://tareksamerr-cmd.github.io/Docs/

theme:
  name: material
  language: ar
  direction: rtl

  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7
        name: التبديل إلى الوضع الليلي

    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-4
        name: التبديل إلى الوضع الفاتح

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.action.edit

docs_dir: docs/
